CREATE TABLE Employees (
  Age INTEGER NOT NULL,
  Department TEXT NOT NULL,
  FullTime TEXT NOT NULL,
  ID INTEGER NOT NULL PRIMARY KEY,
  Name TEXT NOT NULL,
  Salary INTEGER NOT NULL,
  StartDate TEXT NOT NULL
);
